DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS product_category CASCADE;
DROP TABLE IF EXISTS favorite_items CASCADE;
DROP TABLE IF EXISTS products CASCADE;